import threading
import time
import yaml
import logging
from typing import List, Callable
from omegaconf import DictConfig

from .states.bodhi import BodhiGraphMetadata,BodhiState
from .structured_text_detection.structured_text_detection import evaluate_text_units
from .subgraphs.graph_extraction import create_extraction_subgraph

from .utils import get_llm_from_config, estimate_tokens
from Sanchayam import Sanchayam

logger = logging.getLogger(__name__)

def extract_knowledge_graph_parallel(
    paths: dict,
    storage: Sanchayam,
    config: DictConfig,
    parent_trace_id: int,
    text_extraction_func: Callable,
    max_num_threads: int = 12, # Increasing thread count beyond 12 would hit vertex ai rate limiter
    entity_types: list = None  # If full ontology discovery is required, pass an empty list. Passing None will use default entity types. For custom ontology, pass a list of entity types.
):
    """
    Performs the map-reduce process to extract a knowledge graph from a source document in parallel.

    This function orchestrates the entire process:
    1.  **Setup**: Initializes logging, configuration, and necessary paths.
    2.  **Pre-computation**: Checks if text units (chunks) are already processed. If not, it
        extracts them from the source document and saves them.
    3.  **Map Phase**: Splits the text chunks among multiple threads. Each thread invokes a
        LangGraph graph to process its assigned chunks independently.
    4.  **Reduce Phase**: After all threads complete extraction, system combines the intermediate results
        generated by each thread into a final, consolidated output.

    Args:
        source (str): The base name of the source file (e.g., "Fusion_Physics").
        storage (Sanchayam): An instance of the storage client for file operations.
        parent_trace_id (int): A unique identifier for the parent trace of this operation.
        text_extraction_func (Callable): A function that takes a file path and token limit,
                                         and returns a list of text chunks.
        max_num_threads (int, optional): The number of parallel threads to use. Defaults to 12.
        entity_types (list, optional):  A list of entity types to be used in the graph extraction.
                                        If None, default entity types will be used.
                                        If full ontology discovery is required, pass an empty list.
    """
    start_time = time.time()
    # --- 1. Initial Setup ---
    source_name = paths.get("source_name")  # Remove file extension
    data_dir = "data"
    text_unit_path = paths.get("text_unit_path")
    
    # Entity type ontology for Bodhi
    if entity_types is not None: 
        default_entity_types = entity_types
    else:
        default_entity_types = ["Concepts","Components","Processes","DataTypes","Inputs and Outputs",
                    "Configuration and Parameters","Entities (Real-World Objects)","Validation and Evaluation",
                "Technologies and Frameworks","Constraints and Requirement","Results and Outcomes"]
    

    llm = get_llm_from_config(config)
    thinking_llm = get_llm_from_config(config,model_type="thinking")

    
    logger.info(f"Starting parallel graph extraction for source: {paths.get("source")}")

    # --- 2. Load or Generate Text Chunks ---
    if storage.file_exists(path=text_unit_path):
        logger.info(f"Found existing text units at: {text_unit_path}. Loading them.")
        text_units_raw = storage.read_file(path=text_unit_path)
        text_units_n_summary = yaml.safe_load(text_units_raw)

        text_units = [""]* len(text_units_n_summary["text_units"].keys())
        for i,unit in text_units_n_summary["text_units"].items():
                # print(f"len(text_units_n_summary.keys()): {len(text_units_n_summary.keys())}\nlen(text_units): {len(text_units)}")
                
                # If summary is present for the text unit, use it. Otherwise load text unit
                if unit["summary"] is not None:
                    text_units[i] = unit["summary"]
                else:
                    text_units[i] = unit["text_unit"]
            
    else:
        """--- 1. Preprocessing ---"""
        logger.info("No pre-existing text units found. Extracting from source document.")
        source_document_path = f"{data_dir}/{paths.get("source_path")}"

        if storage.file_exists(path=source_document_path):
            absolute_file_path = storage.get_absolute_path(path=source_document_path)
            
            ref_sep_raw_text_path = paths.get("ref_separated_raw_text_path")
            raw_text_path = paths.get("raw_text_path")
            """
            1.1 Text extraction and chunking
            |-- Convert source to text
            |  |-- If source document is in pdf format, the callback function uses pymupdf4llm package to extract text from the pdf file.
            |  |-- If source document is already in some text format(.md,.txt,.yml etc) load the file. 
            |-- Then convert the text document into chunks based on token limit
            |  |-- We use spacy to identify sentence boundaries. Text chunks are extracted according to the sentence boundaries. This helps to reduce meaningless fragmentation of sentences across chunks.
            |-- Text extraction and chunking is designed as an injectable dependency(callback) function.
            |  |-- Easy to integrate better/different text extraction/chunking interface. Only constraint is to maintain inputs and outputs of the callback.
            """
            # Call the provided function to perform text extraction and chunking
            extraction_results = text_extraction_func(file_path=absolute_file_path,token_limit=config["token_limit"])
            
            text_units = extraction_results.get('text_units', [])
            raw_text = extraction_results.get('raw_text', "")
            ref_separated_raw_text = extraction_results.get("ref_separated_raw_text")

            """
            1.2 Priming
            |-- Knowledge Graph Priming Process, is designed to generate a concise, domain-specific Priming Summary from a source document excerpt. This summary acts as a foundational, high-fidelity contextual guide for the downstream Entity and Relationship extractors, focusing on core terminology, technical definitions, and inherent structural connections to ensure consistent entity typing and accurate relationship linking across the entire document.
            """
            # now generate a concise summary about the source 
            priming_llm = get_llm_from_config(config=config,model_type="generic")
            summary = _generate_priming_summary(llm=priming_llm,text_units=text_units,token_limit=2000)
            
            """
            1.3 Outlier text unit summarization
            |-- Identify text units with high cognitive complexity/highly structured data. Summarize them using LLM. Store this summary instead of raw text units in the text_units dictionary.
            """
            # find outlier text units 
            outlier_text_units = evaluate_text_units(text_units=text_units)
            text_unit_with_summaries = _generate_final_text_units(text_units,outlier_text_units,llm=llm)
            for i,unit in text_unit_with_summaries.items():
                if unit["summary"] is not None:
                    text_units[i] = unit["summary"]
            # Outlier logic end


            text_units_n_summary = {"text_units":text_unit_with_summaries,"summary":summary}
            
            if not isinstance(text_units, list) or len(text_units) == 0:
                raise ValueError(f"Text extraction failed for {absolute_file_path}. No chunks were generated.")

            # Save the raw text to a YAML file
            text_bytes = b"".join(s.encode('utf-8') for s in yaml.dump(raw_text)) # convert to bytes
            storage.save_file(path=raw_text_path,
                            data=text_bytes)
            
            text_bytes = b"".join(s.encode('utf-8') for s in yaml.dump(ref_separated_raw_text)) # convert to bytes
            storage.save_file(path=ref_sep_raw_text_path,
                            data=text_bytes)
            
            # Save the newly extracted chunks for future runs
            text_unit_n_summary_bytes = yaml.dump(text_units_n_summary, encoding='utf-8')
            storage.save_file(path=text_unit_path, data=text_unit_n_summary_bytes)
            logger.info(f"Extracted and saved {len(text_units)} text units to {text_unit_path}")
        else:
            raise FileNotFoundError(f"Source document does not exist at the expected path: {source_document_path}")
    """
    2. Parallel KG extraction
    |-- 2.1 Map
    |-- 2.2 kg_extraction_graph threads
    |-- 2.3 Reduce
    """
    
    """
    2.2.1 kg_extraction_graph thread function
    |-- invoke_graph_in_thread functions is shared between all the threads
    |-- Prepares langgraph state and metadata. Then invokes the kg_extraction_graph callback to extract knowledge graph. 
    |   |-- kg_extraction_graph is implemented as a callback for modularity. 
        |-- Given the inputs and outputs remain consistent, kg_extraction_graph function implementation can be altered without affecting the overall system. This is implemented in graph_extraction.py
    """
    kg_extraction_graph = create_extraction_subgraph(prompt_path=paths.get("prompt_path"))

    def invoke_graph_in_thread(kg_extraction_graph, thread_id, text_unit, parent_trace_id, llm,thinking_llm, storage,priming_summary=None):
        """Function executed by each thread to process its chunk of text."""
       
        thread_logger = logging.getLogger(f"Thread {thread_id}")
        llm_logger = logging.getLogger(f"Thread {thread_id} LLM")



        metadata = BodhiGraphMetadata(
            text_units=text_unit,
            logger=thread_logger,
            llm_logger = llm_logger,
            llm=llm,
            thinking_llm=thinking_llm,
            storage=storage,
            trace_id=parent_trace_id,
            thread_id=thread_id,
            priming_flag=config.get("priming",False)
        )
        state = BodhiState(
            source_path=paths.get("source_path"),
            source_name=source_name,
            text_units=text_unit,
            summary=priming_summary,
            entity_types=default_entity_types,
            chunk_index=0,
            text_unit_path=text_unit_path,
            metadata=metadata
        )
        thread_start_time = time.time()
        kg_extraction_graph.invoke(input=state, config={"recursion_limit": config.get("graph_recursion_limit",1000)})
        thread_end_time = time.time()
        elapsed_time = thread_end_time - thread_start_time

        thread_logger.info(f"===Thread-{thread_id}===\nTotal number of chunks processed : {len(text_unit)}\nTotal time taken for extraction : {elapsed_time}\n")

    """
    2.1 Map 
    |-- Allocate minimum number of text chunks uniformly across the threads. 
    |-- If total number of text chunks is is not a multiplier of number of threads, remainder is uniformly distributed across first n threads.
    |-- The system is observed to operate faster with minimum number of text units per thread
    |-- To maximize throughput, increase the number of threads up to the limit imposed by the LLM rate limiter and host system capabilities. This action will naturally reduce the number of chunks processed per thread.
    |-- NOTE: We use 18 threads. This limit is derived from the rate limits imposed by Vertex AI, and empirical testing showed marginal throughput gain beyond this number is insignificant.
    """
    threads = []
    # check if number of chunks is less than maximum number of threads. 
    # if yes, then set number of threads to number of chunks. Otherwise, set it to maximum number of threads
    num_threads = min(max_num_threads, len(text_units))

    # Calculate the base size and the number of threads that will get an extra chunk.
    base_size = len(text_units) // num_threads
    remainder = len(text_units) % num_threads
    
    # create a list of length num_threads with base size as all elements
    number_of_chunks_per_thread = [base_size] * num_threads
    # distribute the remainder chunks to the first 'remainder' threads
    for i in range(remainder):
        number_of_chunks_per_thread[i] += 1

    logger.info(
        f"Total chunks: {len(text_units)}, Threads: {num_threads}. "
        f"Distribution: {remainder} threads get {base_size + 1} chunks, "
        f"and {num_threads - remainder} threads get {base_size} chunks."
        f" Chunks per thread: {number_of_chunks_per_thread}"
    )

    """
    2.2.2 KG extraction - Execution
    |-- For now we use custom thread orchestration instead of high level modules like Joblib
    |   |-- KG extraction process of each text unit is expected to take more or less similar time (Each text unit is of similar token length.)
    """
    current_index = 0  # Track the current index in the text_units list
    for i in range(num_threads):
        # 1. Determine the size for this specific thread.
        # The first 'remainder' threads get one extra chunk.
        chunk_size = base_size + 1 if i < remainder else base_size

        # 2. Slice the list based on the current position and calculated size.
        start_index = current_index
        end_index = start_index + chunk_size
        thread_text_chunk = text_units[start_index:end_index]
        # 3. Update the current index for the next thread's starting point.
        current_index = end_index

        # Ensure we don't start a thread with no work
        if not thread_text_chunk:
            continue

        thread = threading.Thread(
            target=invoke_graph_in_thread,
            args=(kg_extraction_graph, 
                  i, 
                  thread_text_chunk, 
                  parent_trace_id, 
                  llm,thinking_llm, 
                  storage,
                  text_units_n_summary["summary"])
        )
        threads.append(thread)
        thread.start()

    for thread in threads:
        thread.join()

    logger.info("All mapping threads have finished processing. Now combining intermediate files...")
    """
    2.3 Reduce 
    |-- KG extraction step saves independent intermediate files in YAML format. 
    |-- _reduce_intermediate_files function read each of these files and combine them into one YAML file.
    |-- Output of this step is a YAML file stored at a predefined location
    """
    # --- 4. Reduce Phase: Combine Intermediate Files ---
    intermediate_graph= _reduce_intermediate_files(paths=paths,
                                                  storage=storage, 
                                                  num_threads=num_threads,
                                                  number_of_chunks_per_thread=number_of_chunks_per_thread)

    # log intermediate graph as debug information
    
    end_time = time.time()
    elapsed_time = end_time - start_time
    
    # logger.debug(f"Combined graph data: {intermediate_graph}.")
    logger.info(
        f"\n==== Knowledge Graph Extraction Report (extract_knowledge_graph_parallel) ====\n"
        f"Source: {source_name}\n"
        f"Total Chunks Processed: {len(text_units)}\n"
        f"Threads Used: {num_threads}\n"
        f"Chunks per Thread: {number_of_chunks_per_thread}\n"
        f"Entities Extracted: {len(intermediate_graph.get('entities', []))}\n"
        f"Relationships Extracted: {len(intermediate_graph.get('relationships', []))}\n"
        f"Combined Intermediate File: {paths.get('interm_data_path')}\n"
        f"Total Time Taken: {elapsed_time:.2f} seconds\n"
        f"=========================================="
    )
    return intermediate_graph



def _generate_priming_summary(
    text_units: List[str],
    token_limit: int,
    llm,
    summary_token_limit=500
    ) -> str:
    """
    Generate a priming summary for Bodhi's KG extraction.

    Args:
        text_units: List of text chunks from the source document.
        token_limit: Max tokens allowed for concatenated text input.
        llm: An initialized ChatGoogleGenerativeAI object.
        model_name: Model name for token counting.
    
    Returns:
        A summary (≤ 500 tokens) highlighting essential context
        for entity & relationship extraction in Bodhi.
    """
    # Step 1: Collect first N text units under token_limit
    combined_text = ""
    for unit in text_units:
        if estimate_tokens(combined_text + " " + unit) < token_limit:
            combined_text += " " + unit
        else:
            break

    # Step 2: Prepare prompt for LLM
    prompt = f"""
You are assisting in building a high-quality Knowledge Graph from a research paper.
The following text is an excerpt from the document.

Your task:
- Create a concise summary (≤ {summary_token_limit} tokens) capturing key domain concepts.
- The summary should be suitable as a priming context for an AI system (Bodhi) that will later extract entities and relationships from the rest of the document.
- Focus on terminology, technical definitions, and structural connections that will guide consistent entity type identification and relationship linking.

Text excerpt:
\"\"\"{combined_text.strip()}\"\"\"
    """

    # Step 3: Get response from LLM
    response = llm.invoke(prompt)
    logger.info(f"Priming summary: \n{response.content}\n")
    return response.content

def _generate_final_text_units(text_units,
                               outlier_text_units,
                               llm,
                               token_limit=500):
    outlier_indices = [item["index"] for item in outlier_text_units if item["is_structured"]==True]
    logger.info(f"outlier indices : {outlier_indices}")
    outlier_text_unit_dict = {i:unit for i,unit in enumerate(text_units) if i in outlier_indices}
    summarized_outlier_units = _generate_text_unit_summary(text_units=outlier_text_unit_dict,
                                                           llm=llm,
                                                           token_limit=token_limit)
    summarized_outlier_units_dict = {}
    for i,unit in enumerate(text_units):
        summarized_outlier_units_dict[i] = {"text_unit":unit,"summary":summarized_outlier_units.get(i,None)}
    
    return summarized_outlier_units_dict

def _generate_text_unit_summary(
    text_units, # dictionary
    llm,
    token_limit,
    ) -> str:
    """
    Generate a summary for Bodhi's KG extraction.

    Args:
        text_units: List of text chunks from the source document.
        token_limit: Max tokens allowed for concatenated text input.
        llm: An initialized ChatGoogleGenerativeAI object.
        model_name: Model name for token counting.
    
    Returns:
        A summary (≤ 500 tokens) highlighting essential context
        for entity & relationship extraction in Bodhi.
    """
    # Step 1: Collect first N text units under token_limit
    summary_dict = {}
    for i,unit in text_units.items():
        # Step 2: Prepare prompt for LLM
        prompt = f"""
You are assisting in building a high-quality Knowledge Graph from a research paper.
The following text is an excerpt from the document.

Your task:
- Create a concise summary (≤ {token_limit} tokens) capturing key domain concepts.
- Focus on terminology, technical definitions, and structural connections that
will guide consistent entity extraction, entity type identification and relationship linking.

Text excerpt:
\"\"\"{unit.strip()}\"\"\"
    """
        # Step 3: Get response from LLM
        response = llm.invoke(prompt)
        logger.info(f"Concise summary: \n{response.content}\n")
        summary_dict[i] = response.content
    return summary_dict

def _reduce_intermediate_files(paths, storage, num_threads, number_of_chunks_per_thread):
    """
    Combines intermediate YAML files from multiple threads into a single file, adjusting chunk indices based on thread ID.
    """
    all_chunk_indices = []
    all_entities = []
    all_relationships = []

    source_name = paths.get("source_name")  
    # Get the graph info storage path
    graph_info_storage = paths.get("graph_info_storage")
    offset = 0

    for thread_id in range(num_threads):
        # Construct the path to the intermediate file for the current thread
        interm_data_path = f"{graph_info_storage}/{thread_id}/{source_name}_intermediate_data.yml"
        
        # Check if the file exists before processing
        if not storage.file_exists(interm_data_path):
            logger.warning(f"Intermediate file not found for thread {thread_id}: {interm_data_path}")
            continue

        f = storage.read_file(path= interm_data_path)
        thread_data = yaml.safe_load(f)

        if not thread_data:
            logger.warning(f"Intermediate file for thread {thread_id} is empty.")
            continue
            
        # Calculate the chunk index offset for this thread

        logger.info(f"Processing thread {thread_id} with offset {offset}")
        
        # Adjust chunk indices and add to the master list
        for index in thread_data.get('chunk_indices', []):
            all_chunk_indices.append(index + offset)
            
        # Adjust source chunk indices for entities and add to the master list
        for entity in thread_data.get('entities', []):
            entity['source_chunk_index'] += offset
            all_entities.append(entity)
        for relationship in thread_data.get('relationships', []):
            # Adjust source chunk index for relationships
            if 'source_chunk_index' in relationship:
                relationship['source_chunk_index'] += offset
            all_relationships.append(relationship)
        
        offset += number_of_chunks_per_thread[thread_id]
            
    # Create the final combined dictionary
    combined_data = {
        'chunk_indices': all_chunk_indices,
        'entities': all_entities,
        'relationships': all_relationships
    }
    
    # Define the output path for the combined file
    combined_file_path = f"{graph_info_storage}/{source_name}_combined_intermediate_data.yml"
    

    # Write the combined data to a new YAML file
    text_unit_bytes = yaml.dump(combined_data, encoding='utf-8')
    storage.save_file(path=combined_file_path, data=text_unit_bytes)
    logger.info(f"Successfully combined {num_threads} intermediate files into {combined_file_path}")
    return combined_data  # Return the combined data for further processing or verification
